WIP - changes to use mapcloud authentication
thinkWhere/OsmaWebServices-QGIS-Plugin pull request #1
Opened 2017-04-16 13:00 UTC by mattkernow

- WMTS not yet supported
- Fax number is not present in GetCapabilities
- Password stored as plain text in the registry
- Preview images need renaming to match layers (or preview func can be removed)

2017-05-01 12:12 UTC, rightway1 reviewed
A bunch of picky docs comments, but otherwise looks good.  Works for me in 2.14 and 2.18 64bit.  Assume the preview is just disabled until the samples can be updated?

2017-05-01 12:12 UTC, rightway1 commented on README.md
>  [OSMA Web Services Wiki](http://wms.locationcentre.co.uk/wiki/index.php/OSMA_Web_Services)
The address for the help will be changing - probably to http://osmahelp.themapcloud.com

2017-05-01 12:12 UTC, rightway1 commented on TheMapCloudWebServices/__init__.py
> + Easy add OSMA WMS and WMTS layers_wms to QGIS
just "layers" not layers_wms

2017-05-01 12:12 UTC, rightway1 commented on TheMapCloudWebServices/layers.py
> +    Custom delegate to add a push button to a
to a....?

2017-05-01 12:12 UTC, rightway1 commented on TheMapCloudWebServices/layers.py
> +    """Add layers_wms to QGIS map canvas"""
Just "layers"?

2017-05-01 12:12 UTC, rightway1 commented on TheMapCloudWebServices/layers.py
> +                # Adds multiple layers_wms to canvas as single layer
"layers"

2017-05-01 12:12 UTC, rightway1 commented on TheMapCloudWebServices/osma_web_services.py
> + Easy add OSMA WMS and WMTS layers_wms to QGIS
"layers"

2017-05-01 12:12 UTC, rightway1 commented on TheMapCloudWebServices/osma_web_services_dialog.py
> + Easy add OSMA WMS and WMTS layers_wms to QGIS
"layers"

2017-05-01 12:12 UTC, rightway1 commented on TheMapCloudWebServices/plugin.cfg
> +help_url = https://api.themapcloud.com
help_url will be changing from wiki to static help pages

2017-05-01 12:12 UTC, rightway1 commented on TheMapCloudWebServices/populate_qtreeview.py
> +        # Add layers_wms to correct category
Layers

2017-05-01 13:01 UTC, alastaircarson commented on TheMapCloudWebServices/layers.py
>  class PreviewButton(QStyledItemDelegate):
Preview button been removed? Should this be tidied up?

2017-05-01 13:02 UTC, alastaircarson commented on TheMapCloudWebServices/mapcloud_authentication.py
> +
Saw a QGIS crash when this dialog was shown after a reset. Not sure what happened

2017-05-01 13:03 UTC, alastaircarson commented on TheMapCloudWebServices/osma_plugin.cfg
> +help_url = http://wms.locationcentre.co.uk/wiki/index.php/OSMA_Web_Services
Clicking on the WIKI button caused the API docs to be shown rather than the wiki!

2017-05-01 13:08 UTC, alastaircarson commented on TheMapCloudWebServices/osma_web_services.py
>          self.pop_wms.clear_tree()
Reset button didn't seem to clear the tree?

2017-05-01 13:13 UTC, alastaircarson requested changes
I can see that I was using the wrong config file, but still found a couple of issues.

Alastair

2017-05-01 13:15 UTC, alastaircarson commented on TheMapCloudWebServices/osma_plugin.cfg
> +help_url = http://wms.locationcentre.co.uk/wiki/index.php/OSMA_Web_Services
Okay, I can see that I had the wrong config file!

2017-05-01 13:40 UTC, alastaircarson commented on TheMapCloudWebServices/mapcloud_authentication.py
> +        self.mc_auth_dlg.ui.loginPushButton.clicked.connect(self.check_auth_credentials)
Cancel button doesn't seem to do anything

2017-05-03 08:19 UTC, rightway1 commented on README.md
>  [OSMA Web Services Wiki](http://wms.locationcentre.co.uk/wiki/index.php/OSMA_Web_Services)
http://osmahelp.themapcloud.com is now set up so it should be safe to use this as the URL for now.

2017-05-03 20:24 UTC, mattkernow commented on TheMapCloudWebServices/osma_web_services.py
>          self.pop_wms.clear_tree()
It never did, will try and figure this one out at some point.

2017-05-03 20:24 UTC, mattkernow commented on TheMapCloudWebServices/mapcloud_authentication.py
> +        self.mc_auth_dlg.ui.loginPushButton.clicked.connect(self.check_auth_credentials)
Fixed

2017-05-03 20:25 UTC, mattkernow commented on TheMapCloudWebServices/mapcloud_authentication.py
> +
Cannot reproduce on 2.14 64bit Linux

2017-05-03 20:26 UTC, mattkernow commented on README.md
>  [OSMA Web Services Wiki](http://wms.locationcentre.co.uk/wiki/index.php/OSMA_Web_Services)
Done

2017-05-03 20:26 UTC, mattkernow commented on TheMapCloudWebServices/__init__.py
> + Easy add OSMA WMS and WMTS layers_wms to QGIS
fixed

2017-05-03 20:26 UTC, mattkernow commented on TheMapCloudWebServices/layers.py
> +    Custom delegate to add a push button to a
fixed

2017-05-03 20:26 UTC, mattkernow commented on TheMapCloudWebServices/layers.py
> +    """Add layers_wms to QGIS map canvas"""
fixed

2017-05-03 20:26 UTC, mattkernow commented on TheMapCloudWebServices/layers.py
> +                # Adds multiple layers_wms to canvas as single layer
fixed

2017-05-03 20:26 UTC, mattkernow commented on TheMapCloudWebServices/osma_web_services.py
> + Easy add OSMA WMS and WMTS layers_wms to QGIS
fixed... find and replace gone wrong i think :)

2017-05-03 20:27 UTC, mattkernow commented on TheMapCloudWebServices/osma_web_services_dialog.py
> + Easy add OSMA WMS and WMTS layers_wms to QGIS
fixed

2017-05-03 20:27 UTC, mattkernow commented on TheMapCloudWebServices/plugin.cfg
> +help_url = https://api.themapcloud.com
I'll leave this as is for now, probably want to change per deployment to our QGIS repo

2017-05-03 20:27 UTC, mattkernow commented on TheMapCloudWebServices/populate_qtreeview.py
> +        # Add layers_wms to correct category
fixed

2017-05-03 20:29 UTC, mattkernow commented on TheMapCloudWebServices/layers.py
>  class PreviewButton(QStyledItemDelegate):
I have removed some of the preview code, however, as I dont have the original UI files I cant remove the button easily. So I have had to leave some code in to disable on startup.

2017-05-03 20:30 UTC, mattkernow commented on TheMapCloudWebServices/layers.py
>  class PreviewButton(QStyledItemDelegate):
Also its spaghetti code so might be safer to leave in

2017-05-04 09:36 UTC, alastaircarson approved these changes

2017-05-04 09:36 UTC, merged

2017-05-04 09:36 UTC, alastaircarson commented
Thanks Matt